name: '🚔'
on: [ push, pull_request ]
jobs:
  verify:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-go@v3.5.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - run: |
          go vet -v ./...
          go build -v ./...
          go test -v ./...
